### ISSUE TITLE
Not able to use governor with cukespace 

### ISSUE THREAD

**Issue by punitbisht** [arquillian/arquillian-governor#44]
##### Issue Overview

Jira issue is not updating , getting exceptions 

##### Expected Behaviour
Jira issue should be updated when test pass 

##### Current Behaviour

Nothing is happening in Jira 

##### arquillian.xml file 
`<extension qualifier="governor-jira">
        <property name="username">puneet.bisht@pearson.com</property>
        <property name="password">Pearson123</property>
        <property name="server">https://mycompany.jira.com/</property>
        <property name="force">true</property>
        <property name="closePassed">true</property>
    </extension>`

#### pom.xml 

`<dependency>
            <groupId>org.arquillian.extension</groupId>
            <artifactId>arquillian-governor-jira</artifactId>
            <version>1.0.0.Final</version>
            <scope>test</scope>

        </dependency>`

#### Console Output when I run a test 
```
Configuration of Arquillian Governor extension: 
ignore                                   false
ignoreOnly

15:01:09.885 [main] DEBUG c.a.j.r.c.i.a.AsynchronousHttpClientFactory$MavenUtils - Could not find version for maven artifact com.atlassian.jira:jira-rest-java-com.atlassian.jira.rest.client
15:01:09.893 [main] DEBUG c.a.j.r.c.i.a.AsynchronousHttpClientFactory$MavenUtils - Got the following exception
java.lang.NullPointerException: null
at java.util.Properties$LineReader.readLine(Properties.java:434) ~[na:1.8.0_121]
at java.util.Properties.load0(Properties.java:353) ~[na:1.8.0_121]
at java.util.Properties.load(Properties.java:341) ~[na:1.8.0_121]
at com.atlassian.jira.rest.client.internal.async.AsynchronousHttpClientFactory$MavenUtils.getVersion(AsynchronousHttpClientFactory.java:158) ~[com.atlassian.jira.rest.client-2.0.0-m31.w2.jar:na]
at com.atlassian.jira.rest.client.internal.async.AsynchronousHttpClientFactory$RestClientApplicationProperties.getVersion(AsynchronousHttpClientFactory.java:121) [com.atlassian.jira.rest.client-2.0.0-m31.w2.jar:na]
at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClient.getUserAgent(DefaultHttpClient.java:168) [com.atlassian.jira.rest.client-2.0.0-m31.w2.jar:na]
at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClient.<init>(DefaultHttpClient.java:139) [com.atlassian.jira.rest.client-2.0.0-m31.w2.jar:na]
at com.atlassian.jira.rest.client.internal.async.AsynchronousHttpClientFactory.createClient(AsynchronousHttpClientFactory.java:53) [com.atlassian.jira.rest.client-2.0.0-m31.w2.jar:na]
at com.atlassian.jira.rest.client.internal.async.AsynchronousJiraRestClientFactory.create(AsynchronousJiraRestClientFactory.java:35) [com.atlassian.jira.rest.client-2.0.0-m31.w2.jar:na]
at org.arquillian.extension.governor.jira.impl.JiraGovernorClientFactory.build(JiraGovernorClientFactory.java:61) [arquillian-governor-jira-1.0.0.Final.jar:1.0.0.Final]
at org.arquillian.extension.governor.jira.configuration.JiraGovernorConfigurator.onGovernorExtensionConfigured(JiraGovernorConfigurator.java:71) [arquillian-governor-jira-1.0.0.Final.jar:1.0.0.Final]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96) [arquillian-core-impl-base-1.1.13.Final.jar:1.1.13.Final]
at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103) [arquillian-core-impl-base-1.1.13.Final.jar:1.1.13.Final]
at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:85) [arquillian-core-impl-base-1.1.13.Final.jar:1.1.13.Final]
at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:143) [arquillian-core-impl-base-1.1.13.Final.jar:1.1.13.Final]
at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:114) [arquillian-core-impl-base-1.1.13.Final.jar:1.1.13.Final]
at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67) [arquillian-core-impl-base-1.1.13.Final.jar:1.1.13.Final]
at org.arquillian.extension.governor.configuration.GovernorConfigurator.onArquillianDescriptor(GovernorConfigurator.java:71) [arquillian-governor-1.0.0.Final.jar:1.0.0.Final]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96) [arquillian-core-impl-base-1.1.13.Final.jar:1.1.13.Final]
at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103) [arquillian-core-impl-base-1.1.13.Final.jar:1.1.13.Final]
at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:85) [arquillian-core-impl-base-1.1.13.Final.jar:1.1.13.Final]
at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:143) [arquillian-core-impl-base-1.1.13.Final.jar:1.1.13.Final]
at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:114) [arquillian-core-impl-base-1.1.13.Final.jar:1.1.13.Final]
at org.jboss.arquillian.core.impl.ManagerImpl.bindAndFire(ManagerImpl.java:263) [arquillian-core-impl-base-1.1.13.Final.jar:1.1.13.Final]
at org.jboss.arquillian.core.impl.InstanceImpl.set(InstanceImpl.java:74) [arquillian-core-impl-base-1.1.13.Final.jar:1.1.13.Final]
at org.jboss.arquillian.config.impl.extension.ConfigurationRegistrar.loadConfiguration(ConfigurationRegistrar.java:73) [arquillian-config-impl-base-1.1.13.Final.jar:1.1.13.Final]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96) [arquillian-core-impl-base-1.1.13.Final.jar:1.1.13.Final]
at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103) [arquillian-core-impl-base-1.1.13.Final.jar:1.1.13.Final]
at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:85) [arquillian-core-impl-base-1.1.13.Final.jar:1.1.13.Final]
at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:143) [arquillian-core-impl-base-1.1.13.Final.jar:1.1.13.Final]
at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:114) [arquillian-core-impl-base-1.1.13.Final.jar:1.1.13.Final]
at org.jboss.arquillian.core.impl.ManagerImpl.start(ManagerImpl.java:288) [arquillian-core-impl-base-1.1.13.Final.jar:1.1.13.Final]
at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.<init>(EventTestRunnerAdaptor.java:63) [arquillian-test-impl-base-1.1.13.Final.jar:1.1.13.Final]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_121]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [na:1.8.0_121]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.8.0_121]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [na:1.8.0_121]
at org.jboss.arquillian.test.spi.SecurityActions.newInstance(SecurityActions.java:162) [arquillian-test-spi-1.1.13.Final.jar:1.1.13.Final]
at org.jboss.arquillian.test.spi.SecurityActions.newInstance(SecurityActions.java:103) [arquillian-test-spi-1.1.13.Final.jar:1.1.13.Final]
at org.jboss.arquillian.test.spi.TestRunnerAdaptorBuilder.build(TestRunnerAdaptorBuilder.java:52) [arquillian-test-spi-1.1.13.Final.jar:1.1.13.Final]
at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:114) [arquillian-junit-core-1.1.13.Final.jar:1.1.13.Final]
at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68) [junit-rt.jar:na]
at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51) [junit-rt.jar:na]
at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237) [junit-rt.jar:na]
at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70) [junit-rt.jar:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147) [idea_rt.jar:na]
15:01:10.039 [main] DEBUG o.a.h.i.c.c.CachingHttpAsyncClient - Cache miss [host: https://myCompany.jira.com; uri: https://myCompany.jira.com/rest/api/latest/serverInfo]
15:01:10.039 [main] DEBUG o.a.h.i.c.c.CachingHttpAsyncClient - Calling the backend
15:01:10.079 [main] DEBUG o.a.h.i.n.c.DefaultHttpAsyncClient - [exchange: 1] start execution
15:01:10.083 [main] DEBUG o.a.h.i.n.c.DefaultHttpAsyncClient - [exchange: 1] Request connection for {s}->https://myCompany.jira.com:443
15:01:10.084 [main] DEBUG c.a.h.a.h.DefaultHttpClient$2 - Connection request: [route: {s}->https://myCompany.jira.com:443][total kept alive: 0; route allocated: 0 of 20; total allocated: 0 of 20]
15:01:10.240 [httpclient-io:thread-1] DEBUG c.a.h.a.h.DefaultHttpClient$2 - Connection leased: [id: 1][route: {s}->https://myCompany.jira.com:443][total kept alive: 0; route allocated: 1 of 20; total allocated: 0 of 20]
15:01:10.242 [httpclient-io:thread-1] DEBUG o.a.h.i.n.c.DefaultHttpAsyncClient - [exchange: 1] Connection allocated: [id:1][route:{s}->https://myCompany.jira.com:443][state:null]
15:01:10.287 [httpclient-io:thread-1] DEBUG o.a.h.nio.reactor.ssl.SSLIOSession - http-outgoing-1 10.106.201.170:54180<->104.192.142.67:443[ACTIVE][r:][ACTIVE][NOT_HANDSHAKING][0][0][0][0]: Set attribute http.nio.exchange-handler
15:01:10.288 [httpclient-io:thread-1] DEBUG o.a.h.nio.reactor.ssl.SSLIOSession - http-outgoing-1 10.106.201.170:54180<->104.192.142.67:443[ACTIVE][rw:][ACTIVE][NOT_HANDSHAKING][0][0][0][0]: Event set [w]
15:01:10.288 [httpclient-io:thread-1] DEBUG o.a.h.n.p.HttpAsyncRequestExecutor - http-outgoing-1 [ACTIVE]: Connected
15:01:10.289 [httpclient-io:thread-1] DEBUG o.a.h.nio.reactor.ssl.SSLIOSession - http-outgoing-1 10.106.201.170:54180<->104.192.142.67:443[ACTIVE][rw:][ACTIVE][NOT_HANDSHAKING][0][0][0][0]: Set attribute http.nio.http-exchange-state
15:01:10.289 [httpclient-io:thread-1] DEBUG o.a.h.n.p.HttpAsyncRequestExecutor - http-outgoing-1 [ACTIVE] Request ready
15:01:10.291 [httpclient-io:thread-1] DEBUG o.a.h.i.n.c.DefaultHttpAsyncClient - [exchange: 1] Attempt 1 to execute request
15:01:10.291 [httpclient-io:thread-1] DEBUG o.a.h.nio.reactor.ssl.SSLIOSession - http-outgoing-1 10.106.201.170:54180<->104.192.142.67:443[ACTIVE][rw:][ACTIVE][NOT_HANDSHAKING][0][0][0][0]: Set timeout 20000
15:01:10.292 [httpclient-io:thread-1] DEBUG o.a.h.c.p.RequestClientConnControl - Connection route not set in the context
15:01:10.292 [httpclient-io:thread-1] DEBUG o.a.h.c.protocol.RequestAddCookies - Connection route not set in the context
15:01:10.292 [httpclient-io:thread-1] DEBUG o.a.h.c.protocol.RequestAuthCache - Auth cache not set in the context
15:01:10.292 [httpclient-io:thread-1] DEBUG o.a.h.c.p.RequestProxyAuthentication - Proxy auth state: UNCHALLENGED
15:01:10.292 [httpclient-io:thread-1] DEBUG org.apache.http.headers - http-outgoing-1 >> GET /rest/api/latest/serverInfo HTTP/1.1
15:01:10.293 [httpclient-io:thread-1] DEBUG org.apache.http.headers - http-outgoing-1 >> Authorization: Basic cHVuZWV0LmJpc2h0QHBlYXJzb24uY29tOlBlYXJzb24xMjM=
15:01:10.293 [httpclient-io:thread-1] DEBUG org.apache.http.headers - http-outgoing-1 >> Accept: application/json
15:01:10.293 [httpclient-io:thread-1] DEBUG org.apache.http.headers - http-outgoing-1 >> Via: 1.1 localhost (Apache-HttpClient/4.5.3 (cache))
15:01:10.293 [httpclient-io:thread-1] DEBUG org.apache.http.headers - http-outgoing-1 >> Host: myCompany.jira.com:443
15:01:10.293 [httpclient-io:thread-1] DEBUG org.apache.http.headers - http-outgoing-1 >> User-Agent: Atlassian HttpClient 0.13.2 / Atlassian JIRA Rest Java Client-unknown (0) / Default
15:01:10.293 [httpclient-io:thread-1] DEBUG o.a.h.nio.reactor.ssl.SSLIOSession - http-outgoing-1 10.106.201.170:54180<->104.192.142.67:443[ACTIVE][rw:][ACTIVE][NOT_HANDSHAKING][0][0][0][0]: Event set [w]
15:01:10.293 [httpclient-io:thread-1] DEBUG o.a.h.i.n.c.DefaultHttpAsyncClient - [exchange: 1] Request completed
15:01:10.548 [httpclient-io:thread-1] DEBUG o.a.h.nio.reactor.ssl.SSLIOSession - http-outgoing-1 10.106.201.170:54180<->104.192.142.67:443[ACTIVE][rw:w][ACTIVE][NOT_HANDSHAKING][0][0][349][0]: 320 bytes written
15:01:10.549 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 >> "GET /rest/api/latest/serverInfo HTTP/1.1[\r][\n]"
15:01:10.549 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 >> "Authorization: Basic cHVuZWV0LmJpc2h0QHBlYXJzb24uY29tOlBlYXJzb24xMjM=[\r][\n]"
15:01:10.549 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 >> "Accept: application/json[\r][\n]"
15:01:10.549 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 >> "Via: 1.1 localhost (Apache-HttpClient/4.5.3 (cache))[\r][\n]"
15:01:10.549 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 >> "Host: myCompany.jira.com:443[\r][\n]"
15:01:10.549 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 >> "User-Agent: Atlassian HttpClient 0.13.2 / Atlassian JIRA Rest Java Client-unknown (0) / Default[\r][\n]"
15:01:10.549 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 >> "[\r][\n]"
15:01:10.549 [httpclient-io:thread-1] DEBUG o.a.h.nio.reactor.ssl.SSLIOSession - http-outgoing-1 10.106.201.170:54180<->104.192.142.67:443[ACTIVE][rw:w][ACTIVE][NOT_HANDSHAKING][0][0][349][0]: Event cleared [w]
15:01:10.549 [httpclient-io:thread-1] DEBUG o.a.h.n.p.HttpAsyncRequestExecutor - http-outgoing-1 [ACTIVE] Request ready
15:01:11.090 [httpclient-io:thread-1] DEBUG o.a.h.nio.reactor.ssl.SSLIOSession - http-outgoing-1 10.106.201.170:54180<->104.192.142.67:443[ACTIVE][r:r][ACTIVE][NOT_HANDSHAKING][0][0][0][0]: 977 bytes read
15:01:11.090 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 << "HTTP/1.1 200 OK[\r][\n]"
15:01:11.090 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 << "Server: Atlassian Proxy/0.1.152[\r][\n]"
15:01:11.090 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 << "Vary: Accept-Encoding[\r][\n]"
15:01:11.091 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 << "ATL-vTM-Backend-Time: 457[\r][\n]"
15:01:11.091 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 << "Cache-Control: no-cache, no-store, no-transform[\r][\n]"
15:01:11.091 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 << "Content-Type: application/json;charset=UTF-8[\r][\n]"
15:01:11.091 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 << "Strict-Transport-Security: max-age=315360000; includeSubDomains; preload[\r][\n]"
15:01:11.091 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 << "Date: Thu, 07 Dec 2017 21:01:11 GMT[\r][\n]"
15:01:11.091 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 << "X-AREQUESTID: b140efa8-23ee-43f0-8f71-eb93aa41886f[\r][\n]"
15:01:11.091 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 << "transfer-encoding: chunked[\r][\n]"
15:01:11.091 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 << "ATL-vTM-Time: 543[\r][\n]"
15:01:11.091 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 << "X-AUSERNAME: puneet.bisht[\r][\n]"
15:01:11.091 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 << "X-Content-Type-Options: nosniff[\r][\n]"
15:01:11.091 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 << "Connection: keep-alive[\r][\n]"
15:01:11.091 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 << "Set-Cookie: atlassian.xsrf.token=AG87-S37R-QM8W-6VWE|2d199fee60db5d15b6dfe4981a1b52382bb1cf4a|lin; Path=/; Secure[\r][\n]"
15:01:11.091 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 << "X-Seraph-LoginReason: OK[\r][\n]"
15:01:11.091 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 << "ATL-vTM-Queue-Time: 0[\r][\n]"
15:01:11.091 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 << "[\r][\n]"
15:01:11.091 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 << "13b[\r][\n]"
15:01:11.091 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 << "{"baseUrl":"https://myCompany.jira.com","version":"1001.0.0-SNAPSHOT","versionNumbers":[1001,0,0],"deploymentType":"Cloud","buildNumber":100074,"buildDate":"2017-12-06T18:00:00.000-0600","serverTime":"2017-12-07T15:01:11.027-0600","scmInfo":"e7618fc445aa5e242800b79cff25d95420c245cb","serverTitle":"myCompany.jira.com"}[\r][\n]"
15:01:11.102 [httpclient-io:thread-1] DEBUG org.apache.http.headers - http-outgoing-1 << HTTP/1.1 200 OK
15:01:11.102 [httpclient-io:thread-1] DEBUG org.apache.http.headers - http-outgoing-1 << Server: Atlassian Proxy/0.1.152
15:01:11.102 [httpclient-io:thread-1] DEBUG org.apache.http.headers - http-outgoing-1 << Vary: Accept-Encoding
15:01:11.102 [httpclient-io:thread-1] DEBUG org.apache.http.headers - http-outgoing-1 << ATL-vTM-Backend-Time: 457
15:01:11.102 [httpclient-io:thread-1] DEBUG org.apache.http.headers - http-outgoing-1 << Cache-Control: no-cache, no-store, no-transform
15:01:11.102 [httpclient-io:thread-1] DEBUG org.apache.http.headers - http-outgoing-1 << Content-Type: application/json;charset=UTF-8
15:01:11.102 [httpclient-io:thread-1] DEBUG org.apache.http.headers - http-outgoing-1 << Strict-Transport-Security: max-age=315360000; includeSubDomains; preload
15:01:11.102 [httpclient-io:thread-1] DEBUG org.apache.http.headers - http-outgoing-1 << Date: Thu, 07 Dec 2017 21:01:11 GMT
15:01:11.102 [httpclient-io:thread-1] DEBUG org.apache.http.headers - http-outgoing-1 << X-AREQUESTID: b140efa8-23ee-43f0-8f71-eb93aa41886f
15:01:11.102 [httpclient-io:thread-1] DEBUG org.apache.http.headers - http-outgoing-1 << transfer-encoding: chunked
15:01:11.102 [httpclient-io:thread-1] DEBUG org.apache.http.headers - http-outgoing-1 << ATL-vTM-Time: 543
15:01:11.102 [httpclient-io:thread-1] DEBUG org.apache.http.headers - http-outgoing-1 << X-AUSERNAME: puneet.bisht
15:01:11.103 [httpclient-io:thread-1] DEBUG org.apache.http.headers - http-outgoing-1 << X-Content-Type-Options: nosniff
15:01:11.103 [httpclient-io:thread-1] DEBUG org.apache.http.headers - http-outgoing-1 << Connection: keep-alive
15:01:11.103 [httpclient-io:thread-1] DEBUG org.apache.http.headers - http-outgoing-1 << Set-Cookie: atlassian.xsrf.token=AG87-S37R-QM8W-6VWE|2d199fee60db5d15b6dfe4981a1b52382bb1cf4a|lin; Path=/; Secure
15:01:11.103 [httpclient-io:thread-1] DEBUG org.apache.http.headers - http-outgoing-1 << X-Seraph-LoginReason: OK
15:01:11.103 [httpclient-io:thread-1] DEBUG org.apache.http.headers - http-outgoing-1 << ATL-vTM-Queue-Time: 0
15:01:11.103 [httpclient-io:thread-1] DEBUG o.a.h.n.p.HttpAsyncRequestExecutor - http-outgoing-1 [ACTIVE(322)] Response received
15:01:11.103 [httpclient-io:thread-1] DEBUG o.a.h.i.n.c.DefaultHttpAsyncClient - [exchange: 1] Response received HTTP/1.1 200 OK
15:01:11.107 [httpclient-io:thread-1] DEBUG o.a.h.c.p.ResponseProcessCookies - Cookie spec not specified in HTTP context
15:01:11.107 [httpclient-io:thread-1] DEBUG o.a.h.n.p.HttpAsyncRequestExecutor - http-outgoing-1 [ACTIVE(322)] Input ready
15:01:11.107 [httpclient-io:thread-1] DEBUG o.a.h.i.n.c.DefaultHttpAsyncClient - [exchange: 1] Consume content
15:01:11.107 [httpclient-io:thread-1] DEBUG o.a.h.nio.reactor.ssl.SSLIOSession - http-outgoing-1 10.106.201.170:54180<->104.192.142.67:443[ACTIVE][r:r][ACTIVE][NOT_HANDSHAKING][0][0][0][0]: 0 bytes read
15:01:11.107 [httpclient-io:thread-1] DEBUG o.a.h.nio.reactor.ssl.SSLIOSession - http-outgoing-1 10.106.201.170:54180<->104.192.142.67:443[ACTIVE][r:r][ACTIVE][NOT_HANDSHAKING][0][0][0][0]: 0 bytes read
15:01:11.107 [httpclient-io:thread-1] DEBUG o.a.h.nio.reactor.ssl.SSLIOSession - http-outgoing-1 10.106.201.170:54180<->104.192.142.67:443[ACTIVE][r:r][ACTIVE][NOT_HANDSHAKING][0][0][0][0]: 0 bytes read
15:01:11.107 [httpclient-io:thread-1] DEBUG o.a.h.n.p.HttpAsyncRequestExecutor - http-outgoing-1 [ACTIVE] [chunk-coded; completed: false]
15:01:11.108 [httpclient-io:thread-1] DEBUG o.a.h.n.p.HttpAsyncRequestExecutor - http-outgoing-1 [ACTIVE] Input ready
15:01:11.108 [httpclient-io:thread-1] DEBUG o.a.h.i.n.c.DefaultHttpAsyncClient - [exchange: 1] Consume content
15:01:11.108 [httpclient-io:thread-1] DEBUG o.a.h.nio.reactor.ssl.SSLIOSession - http-outgoing-1 10.106.201.170:54180<->104.192.142.67:443[ACTIVE][r:r][ACTIVE][NOT_HANDSHAKING][0][0][0][0]: 5 bytes read
15:01:11.108 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 << "0[\r][\n]"
15:01:11.108 [httpclient-io:thread-1] DEBUG org.apache.http.wire - http-outgoing-1 << "[\r][\n]"
15:01:11.108 [httpclient-io:thread-1] DEBUG o.a.h.nio.reactor.ssl.SSLIOSession - http-outgoing-1 10.106.201.170:54180<->104.192.142.67:443[ACTIVE][r:r][ACTIVE][NOT_HANDSHAKING][0][0][0][0]: 0 bytes read
15:01:11.108 [httpclient-io:thread-1] DEBUG o.a.h.i.n.c.DefaultHttpAsyncClient - [exchange: 1] Response fully read
15:01:11.109 [httpclient-io:thread-1] DEBUG o.a.h.i.n.c.DefaultHttpAsyncClient - [exchange: 1] Connection can be kept alive indefinitely
15:01:11.109 [httpclient-io:thread-1] DEBUG o.a.h.i.n.c.DefaultHttpAsyncClient - [exchange: 1] Response processed
15:01:11.109 [httpclient-io:thread-1] DEBUG o.a.h.i.n.c.DefaultHttpAsyncClient - [exchange: 1] releasing connection [id:1][route:{s}->https://myCompany.jira.com:443][state:null]
15:01:11.109 [httpclient-io:thread-1] DEBUG o.a.h.nio.reactor.ssl.SSLIOSession - http-outgoing-1 10.106.201.170:54180<->104.192.142.67:443[ACTIVE][r:r][ACTIVE][NOT_HANDSHAKING][0][0][0][0]: Remove attribute http.nio.exchange-handler
15:01:11.109 [httpclient-io:thread-1] DEBUG c.a.h.a.h.DefaultHttpClient$2 - Connection [id: 1][route: {s}->https://myCompany.jira.com:443] can be kept alive indefinitely
15:01:11.109 [httpclient-io:thread-1] DEBUG o.a.h.nio.reactor.ssl.SSLIOSession - http-outgoing-1 10.106.201.170:54180<->104.192.142.67:443[ACTIVE][r:r][ACTIVE][NOT_HANDSHAKING][0][0][0][0]: Set timeout 0
15:01:11.109 [httpclient-io:thread-1] DEBUG c.a.h.a.h.DefaultHttpClient$2 - Connection released: [id: 1][route: {s}->https://myCompany.jira.com:443][total kept alive: 1; route allocated: 1 of 20; total allocated: 1 of 20]
15:01:11.110 [httpclient-io:thread-1] DEBUG o.a.h.i.c.c.CachingHttpAsyncClient - Handling Backend response
15:01:11.115 [httpclient-io:thread-1] DEBUG o.a.h.n.p.HttpAsyncRequestExecutor - http-outgoing-1 [ACTIVE] [chunk-coded; completed: true]
Configuration of Arquillian JIRA extension: 
username                                 puneet.bisht@company.com
server                                   https://myCompany.jira.com/
force                                    true
closePassed                              true
closingMessage                           This JIRA issue was automatically closed by %s with Arquillian Governor JIRA extension.

```

**Comment by smiklosovic** [comment]
Maybe the library for jira in governor does not play well with the jira server instance because it is suitable for other server version
